version: '3'
services:
  home-assistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - /srv/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    network_mode: host
