version: '3'
services:
  influxdb:
    image: influxdb:latest
    volumes:
      - /srv/influxdb:/var/lib/influxdb2
    ports:
      - "8086:8086"
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - /srv/grafana:/var/lib/grafana
    depends_on:
      - influxdb
